# Generated by Django 3.2.9 on 2021-11-16 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211116_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='price',
        ),
    ]
