# Generated by Django 3.2.9 on 2021-11-16 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_productos_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='price',
        ),
    ]
